name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25

      - name: Build JAR
        run: ./gradlew jar --no-daemon

      - name: Get version
        id: version
        if: github.event_name != 'pull_request'
        run: echo "version=$(./gradlew printVersion --no-daemon -q | tail -1)" >> "$GITHUB_OUTPUT"

      - name: Upload JAR to Release
        if: github.event_name != 'pull_request'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.version.outputs.version }}
          name: "Hyacinthusclip ${{ steps.version.outputs.version }}"
          artifacts: "build/libs/hyacinthusclip-${{ steps.version.outputs.version }}.jar"
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
